/**
 * generated by Xtext
 */
package org.palladiosimulator.commons.stoex.formatting;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.eclipse.xtext.xbase.lib.Extension;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#formatting
 * on how and when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
@SuppressWarnings("all")
public class StoExFormatter extends AbstractDeclarativeFormatter {
  @Inject
  @Extension
  private /* StoExGrammarAccess */Object _stoExGrammarAccess;
  
  protected void configureFormatting(final FormattingConfig c) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method findKeywordPairs is undefined for the type StoExFormatter"
      + "\nThe method findKeywordPairs is undefined for the type StoExFormatter"
      + "\nThe method findKeywords is undefined for the type StoExFormatter"
      + "\nThe method findKeywords is undefined for the type StoExFormatter"
      + "\nThe method or field SL_COMMENTRule is undefined for the type StoExFormatter"
      + "\nThe method or field ML_COMMENTRule is undefined for the type StoExFormatter"
      + "\nThe method or field ML_COMMENTRule is undefined for the type StoExFormatter"
      + "\nThe method or field DOTRule is undefined for the type StoExFormatter"
      + "\nfirst cannot be resolved"
      + "\nsecond cannot be resolved"
      + "\nfirst cannot be resolved"
      + "\nsecond cannot be resolved"
      + "\nsecond cannot be resolved"
      + "\nfirst cannot be resolved"
      + "\nsecond cannot be resolved"
      + "\nfirst cannot be resolved"
      + "\nfirst cannot be resolved"
      + "\nsecond cannot be resolved"
      + "\nsecond cannot be resolved");
  }
}
