/*
 * generated by Xtext 2.22.0
 */
package org.palladiosimulator.commons.stoex;

import org.eclipse.xtext.parser.IParser;
import org.palladiosimulator.commons.stoex.parser.PostProcessingStoExParser;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension
 * registry.
 */
public class StoexRuntimeModule extends AbstractStoexRuntimeModule {

    @Override
    public Class<? extends IParser> bindIParser() {
        return PostProcessingStoExParser.class;
    }

}
