/*
 * generated by Xtext 2.22.0
 */
package org.palladiosimulator.commons.stoex;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StoexStandaloneSetup extends StoexStandaloneSetupGenerated {

	public static void doSetup() {
		new StoexStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
    @Override
    public void register(Injector injector) {
        if (!EPackage.Registry.INSTANCE.containsKey(de.uka.ipd.sdq.stoex.StoexPackage.eNS_URI)) {
            EPackage.Registry.INSTANCE.put(de.uka.ipd.sdq.stoex.StoexPackage.eNS_URI, de.uka.ipd.sdq.stoex.StoexPackage.eINSTANCE);
        }
        if (!EPackage.Registry.INSTANCE.containsKey(de.uka.ipd.sdq.probfunction.ProbfunctionPackage.eNS_URI)) {
            EPackage.Registry.INSTANCE.put(de.uka.ipd.sdq.probfunction.ProbfunctionPackage.eNS_URI, de.uka.ipd.sdq.probfunction.ProbfunctionPackage.eINSTANCE
            );
        }
        if (!EPackage.Registry.INSTANCE.containsKey(de.uka.ipd.sdq.units.UnitsPackage.eNS_URI)) {
            EPackage.Registry.INSTANCE.put(de.uka.ipd.sdq.units.UnitsPackage.eNS_URI, de.uka.ipd.sdq.units.UnitsPackage.eINSTANCE);
        }
        
        super.register(injector);
    }
}
