/**
 * generated by Xtext
 */
package org.palladiosimulator.commons.stoex.serializer;

@SuppressWarnings("all")
public class StoExSyntacticSequencer /* implements AbstractStoExSyntacticSequencer  */{
}
