/*
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.commons.stoex


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StoexStandaloneSetup extends StoexStandaloneSetupGenerated {

	def static void doSetup() {
		new StoexStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
