/*
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.commons.stoexNew.ide


/**
 * Use this class to register ide components.
 */
class StoexNewIdeModule extends AbstractStoexNewIdeModule {
}
