/**
 * generated by Xtext
 */
package org.palladiosimulator.commons.stoex.serializer;

import org.palladiosimulator.commons.stoex.serializer.AbstractStoExSyntacticSequencer;

@SuppressWarnings("all")
public class StoExSyntacticSequencer extends AbstractStoExSyntacticSequencer {
}
