/**
 * generated by Xtext
 */
package org.palladiosimulator.commons.stoex.serializer;

import org.palladiosimulator.commons.stoex.serializer.AbstractStoExSemanticSequencer;

@SuppressWarnings("all")
public class StoExSemanticSequencer extends AbstractStoExSemanticSequencer {
}
