/*
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.commons.stoexNew


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StoexNewStandaloneSetup extends StoexNewStandaloneSetupGenerated {

	def static void doSetup() {
		new StoexNewStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
