/*
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.commons.stoexNew.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StoexNewAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/palladiosimulator/commons/stoexNew/parser/antlr/internal/InternalStoexNew.tokens");
	}
}
