/*
 * generated by Xtext 2.22.0
 */
package org.palladiosimulator.commons.stoex.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class StoexProposalProvider extends AbstractStoexProposalProvider {
}
