/*
 * generated by Xtext 2.22.0
 */
package org.palladiosimulator.commons.stoex.ide;


/**
 * Use this class to register ide components.
 */
public class StoexIdeModule extends AbstractStoexIdeModule {
}
