/*
 * generated by Xtext 2.22.0
 */
package org.palladiosimulator.commons.stoex.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.palladiosimulator.commons.stoex.StoexRuntimeModule;
import org.palladiosimulator.commons.stoex.StoexStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class StoexIdeSetup extends StoexStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new StoexRuntimeModule(), new StoexIdeModule()));
	}
	
}
