/*
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.commons.stoexNew.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStoexNewScopeProvider extends DelegatingScopeProvider {
}
