/*
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.commons.stoex.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStoexScopeProvider extends DelegatingScopeProvider {
}
