/*
 * generated by Xtext 2.20.0
 */
package org.palladiosimulator.commons.stoex.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.palladiosimulator.commons.stoex.ui.internal.StoexActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StoexExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(StoexActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		StoexActivator activator = StoexActivator.getInstance();
		return activator != null ? activator.getInjector(StoexActivator.ORG_PALLADIOSIMULATOR_COMMONS_STOEX_STOEX) : null;
	}

}
