/**
 * generated by Xtext
 */
package org.palladiosimulator.commons.stoex.validation;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class StoExValidator /* implements AbstractStoExValidator  */{
}
