/**
 * generated by Xtext
 */
package org.palladiosimulator.commons.stoex.validation;

import org.palladiosimulator.commons.stoex.validation.AbstractStoExValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class StoExValidator extends AbstractStoExValidator {
}
