/*
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.commons.stoexNew.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.palladiosimulator.commons.stoexNew.ui.internal.StoexNewActivator;

public class StoexNewUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StoexNewActivator.getInstance().getInjector("org.palladiosimulator.commons.stoexNew.StoexNew");
	}

}
