/*
* generated by Xtext
*/
package org.palladiosimulator.commons.stoex;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class StoExUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.palladiosimulator.commons.stoex.ui.internal.StoExActivator.getInstance().getInjector("org.palladiosimulator.commons.stoex.StoEx");
	}
	
}
