/*
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.commons.stoexNew.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class StoexNewUiModule extends AbstractStoexNewUiModule {
}
