/*
 * generated by Xtext 2.20.0
 */
package org.palladiosimulator.commons.stoex.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.palladiosimulator.commons.stoex.ui.internal.StoexActivator;

public class StoexUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StoexActivator.getInstance().getInjector("org.palladiosimulator.commons.stoex.Stoex");
	}

}
