/*
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.commons.stoex.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StoexAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/palladiosimulator/commons/stoex/parser/antlr/internal/InternalStoex.tokens");
	}
}
