/*
 * generated by Xtext 2.20.0
 */
package org.palladiosimulator.commons.stoex.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.palladiosimulator.commons.stoex.parser.antlr.internal.InternalStoexParser;
import org.palladiosimulator.commons.stoex.services.StoexGrammarAccess;

public class StoexParser extends AbstractAntlrParser {

	@Inject
	private StoexGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalStoexParser createParser(XtextTokenStream stream) {
		return new InternalStoexParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "expression";
	}

	public StoexGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StoexGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
