/*
 * generated by Xtext 2.12.0
 */
package org.palladiosimulator.commons.stoexNew.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.palladiosimulator.commons.stoexNew.ui.internal.StoexNewActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StoexNewExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return StoexNewActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return StoexNewActivator.getInstance().getInjector(StoexNewActivator.ORG_PALLADIOSIMULATOR_COMMONS_STOEXNEW_STOEXNEW);
	}
	
}
