name: Build Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  Palladio-Core-Commons:
    runs-on: self-hosted
    steps:
      - uses: Nicolas-Boltz/BuildPipelineActionTest@main
        with:
          use-display-output: true
          deploy-updatesite: 'releng/org.palladiosimulator.core-commons.updatesite/target/repository'
          SERVER_SSH_KEY: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
          REMOTE_TARGET: ${{ secrets.DEPLOYMENT_REMOTE_TARGET }}
